Watcher:
  interval: 5000
  baseFolder: drops
  folders:
    - 
      name: drop
      listener: ./lib/schedule_digester
      configuration:
        ftp:
          host: "127.0.0.1"
          port: 21
          username: test
          password: test
